# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"
project_file = ENV["IOS_PROJECT_FILE"] || "./platforms/ios/samplegroceries.xcodeproj"
workspace_file = ENV["IOS_WORKSPACE_FILE"]  || "./platforms/ios/samplegroceries.xcworkspace"
scheme = ENV["SCHEME"] || "samplegroceries"
codesign_identity = "iPhone Distribution: Evan Schultz (4JCC4C7XUG)"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  lane :build_ios do
   match(type: "adhoc", readonly: true, username: "eschultz@rogers.com",  app_identifier: "io.rangle.native-script-cicd-example")
   update_codesign
   gym(export_method: "ad-hoc",
    clean: true,
    configuration: "Release",
    workspace: workspace_file,
    codesigning_identity: codesign_identity,
    export_team_id: ENV["sigh_io.rangle.native-script-cicd-example_adhoc_team-id"],
    scheme: scheme,
    output_directory: "./out",
    output_name: "samplegroceries.ipa",
     xcargs: "PROVISIONING_PROFILE_SPECIFIER='" + ENV["sigh_io.rangle.native-script-cicd-example_adhoc_profile-name"] + "'"
    )

  end

  lane :update_codesign do
    update_xcodeproj(
      xcodeproj: project_file,
      options: {'CODE_SIGN_IDENTITY[sdk=iphoneos*]': codesign_identity})
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
